env:
  node: true
extends: 
  - "airbnb-base"
rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["filename", "dirname"] }]